name: Build and push Docker image to dockerhub

on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: docker build graphs_options_microservice\Dockerfile -t nomaan308/stockoptiongraph:latest
      - name: push image to docker hub
        run: docker push nomaan308/stockoptiongraph:latest
